# fly.toml app configuration file generated for lastpang-backend on 2023-12-24T22:43:09+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "lastpang-backend"
primary_region = "nrt"

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
  [http_service.concurrency]
    type = "requests"
    soft_limit = 250
    hard_limit = 300

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 2048
